name: CI/CD Pipeline AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t veyg/cavemanager .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push veyg/cavemanager

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove all containers using the veyg/cavemanager image
            docker ps -a | awk '{ print $1,$2 }' | grep veyg/cavemanager | awk '{print $1 }' | xargs -I {} docker stop {}
            docker ps -a | awk '{ print $1,$2 }' | grep veyg/cavemanager | awk '{print $1 }' | xargs -I {} docker rm {}

            # Pull the latest image and run it
            sudo docker pull veyg/cavemanager
            sudo docker run -d -e DISCORD_BOT_TOKEN=${{ secrets.BOT_TOKEN }} -v /ebs-data/bot/cavemanager_db:/app/cavemanager_db --name cavemanager veyg/cavemanager

            # Clean up unused (dangling) images
            DANGLING_IMAGES=$(docker images -f "dangling=true" -q)
            if [ ! -z "$DANGLING_IMAGES" ]; then
                docker rmi $DANGLING_IMAGES
            fi
